name: Code quality
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing node modules v${{ matrix.node }}
        run: npm ci

      - name: Linting
        run: npm run lint

  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing node modules v${{ matrix.node }}
        run: npm ci

      - name: Typechecking
        run: npm run typecheck

  format:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing node modules v${{ matrix.node }}
        run: npm ci

      - name: Check code format with prettier
        run: npm run format:check

  prettify:
    needs: [format]
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Prettify
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write --ignore-unknown "."
          only_changed: true
